name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging
  release:
    types: [created]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r Myapp/requirements.txt

      - name: Run tests
        run: pytest Myapp/ --maxfail=1 --disable-warnings -q

  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging (Port 5000)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Ensure screen is installed
            sudo apt update
            sudo apt install -y screen

            cd ~/CI-CD_Pipelines-For-Flask_App || exit 1
            git fetch --all
            git checkout staging
            git pull origin staging

            # Install packages in user environment
            python3 -m venv ~/flask_venv --upgrade-deps || true
            source ~/flask_venv/bin/activate
            pip install --upgrade pip
            pip install -r Myapp/requirements.txt

            # Kill any old Flask process
            pkill -f "python Myapp/app.py" || true

            # Run Flask in detached screen session
            screen -dmS flask_staging bash -c "source ~/flask_venv/bin/activate && PORT=5000 ENV=dev python Myapp/app.py"

  deploy-production:
    if: github.event_name == 'release'
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production (Port 8000)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt update
            sudo apt install -y screen

            cd ~/CI-CD_Pipelines-For-Flask_App || exit 1
            git fetch --all
            git checkout main
            git pull origin main

            python3 -m venv ~/flask_venv --upgrade-deps || true
            source ~/flask_venv/bin/activate
            pip install --upgrade pip
            pip install -r Myapp/requirements.txt

            pkill -f "python Myapp/app.py" || true
            screen -dmS flask_production bash -c "source ~/flask_venv/bin/activate && PORT=8000 ENV=production python Myapp/app.py"
