name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging
  release:
    types: [created]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r Myapp/requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest Myapp/ --maxfail=1 --disable-warnings -q

  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging (Port 5000)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~
            if [ ! -d "CI-CD_Pipelines-For-Flask_App" ]; then
              git clone https://github.com/SHArahul/CI-CD_Pipelines-For-Flask_App.git
            fi
            cd CI-CD_Pipelines-For-Flask_App
            git fetch --all
            git checkout staging
            git pull origin staging

            # Setup virtual environment
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r Myapp/requirements.txt

            # Stop any running Flask app
            pkill -f "python3 app.py" || true

            # Run Flask app in background
            PORT=5000 ENV=dev nohup venv/bin/python Myapp/app.py > flask-staging.log 2>&1 &

  deploy-production:
    if: github.ref == 'refs/heads/main'
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production (Port 8000)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~
            if [ ! -d "CI-CD_Pipelines-For-Flask_App" ]; then
              git clone https://github.com/SHArahul/CI-CD_Pipelines-For-Flask_App.git
            fi
            cd CI-CD_Pipelines-For-Flask_App
            git fetch --all
            git checkout main
            git pull origin main

            # Setup virtual environment
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r Myapp/requirements.txt

            # Stop any running Flask app
            pkill -f "python3 app.py" || true

            # Run Flask app in background
            PORT=8000 ENV=production nohup venv/bin/python Myapp/app.py > flask-production.log 2>&1 &